#!/bin/bash

echo "Bienvenido al ascensor de hotel $(whoami)"
echo "Nos dirigimos hacia arriba"

for ((i=1; i<=17; i++)); do
    sleep 1s
  if [ $i -eq 10 ]; then
    echo "Saltando planta 10"
    continue
  fi
  echo "Estamos en la planta $i"

done
  echo "Hemos llegado"